accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    # [미션] 자유롭게 코드 작성
    # [미션] 필요한 url 경로 작성
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
]

jgDjango/urls.py
from django.contrib import admin
# [코드 추가] re_path 함수 추가로 불러오기
from django.urls import path, include, re_path
# [코드 작성] django.views.static에서 static 파일을 제공하기 위한 serve 함수 불러오기
from django.views.static import serve
# [코드 작성] django.conf에서 settings.py의 개체 가져오기
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

# [코드 작성] DEBUG가 False일 경우 static을 가져올 수 있도록 설정
if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

urlpatterns = [
    path('', views.index, name='index'),
    path('postings/', views.posting_list, name='posting_list'),
    path('posting/create/', views.posting_create, name='posting_create'),
    path('posting/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('posting/<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('posting/<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    path('posting/<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="navbar">
    <div class="navbar__page">
      <span>
        <a href="{% url 'postings:index' %}">
          <img class="navbar__logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
        </a>
      </span>
      <span>
        <a href="{% url 'postings:posting_list' %}">글목록</a>
      </span>
      <span>
        <a href="{% url 'postings:posting_create' %}">글쓰기</a>
      </span>
      <span>
        <a href="{% url 'games:game_list' %}">게임목록</a>
      </span>
    </div>
    <div class="navbar__account">
      {% if user.is_authenticated %}
      <span>
        {{user.username}}님 안녕하세요.
      </span>
      <span>
        <a href="{% url 'accounts:logout' %}" onclick="return userLogout()">로그아웃</a>
      </span>
      {% else %}
        <span>
          <a href="{% url 'accounts:login' %}">로그인</a>
        </span>
        <span>
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </span>
      {% endif %}
    </div>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <script>
    function userLogout() {
      const result = confirm("로그아웃 하시겠습니까?");
      return result;
    }
  </script>
</body>
</html>